CREATE TABLE SYS_DICT
(
    KEY_ID   VARCHAR(32) PRIMARY KEY,
    LABEL    VARCHAR(255) NOT NULL,
    INTRO    VARCHAR(255),
    REVISION INT
);

CREATE TABLE SYS_DICT_ITEM
(
    DICT_KEY VARCHAR(32),
    KEY_ID   VARCHAR(255) PRIMARY KEY,
    LABEL    VARCHAR(255) NOT NULL,
    SORT_NUM VARCHAR(10),
    INTRO    VARCHAR(255),
    REVISION INT
);

/* 插入字典总表[COMMON_EXT_FIELD_TYPE-属性拓展字段数据类型] */
INSERT INTO SYS_DICT(KEY_ID, LABEL, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', '属性拓展字段数据类型', '', 1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_DATE', '日期类型', '1', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_INT', '整数类型', '2', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_VARCHAR', '文本类型', '3', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_ENUM', '枚举类型', '4', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_DATETIME', '日期时间类型', '', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_TEAM', '用户组类型', '', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_USER', '单个用户类型', '', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_USERS', '多个用户类型', '', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('COMMON_EXT_FIELD_TYPE', 'TYPE_FLOAT', '浮点数类型', '', '', 1);

/* 插入字典总表[TrueOrFalse-是否] */
INSERT INTO SYS_DICT(KEY_ID, LABEL, INTRO, REVISION)
VALUES ('TrueOrFalse', '是否', '', 1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('TrueOrFalse', 'TYPE_TRUE', '是', '1', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('TrueOrFalse', 'TYPE_FALSE', '否', '2', '', 1);

/* 插入字典总表[ISSUE_LINK_TYPE-问题链接类型] */
INSERT INTO SYS_DICT(KEY_ID, LABEL, INTRO, REVISION)
VALUES ('ISSUE_LINK_TYPE', '问题链接类型', '', 1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('ISSUE_LINK_TYPE', 'MAIN_TASK', '主任务', '1', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('ISSUE_LINK_TYPE', 'SUB_TASK', '子任务', '2', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('ISSUE_LINK_TYPE', 'BEFORE_TASK', '前置任务', '3', '', 1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY, KEY_ID, LABEL, SORT_NUM, INTRO, REVISION)
VALUES ('ISSUE_LINK_TYPE', 'AFTER_TASK', '后置任务', '4', '', 1);