DROP TABLE IF EXISTS SYS_ROLE;
CREATE TABLE SYS_ROLE
(
    ID        VARCHAR(32)  NOT NULL COMMENT '角色ID;',
    NAMEZH    VARCHAR(255) COMMENT '角色显示名;',
    NAME      VARCHAR(255) COMMENT '角色标识;',
    BE_SYSTEM VARCHAR(255) NOT NULL DEFAULT 'TYPE_FALSE' COMMENT '是否系统预置',
    PRIMARY KEY (ID)
) COMMENT = '角色信息表';



DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER
(
    ID       VARCHAR(32) NOT NULL COMMENT '用户ID',
    NAME     VARCHAR(255) COMMENT '显示名称;',
    NICKNAME VARCHAR(255) COMMENT '昵称;',
    PASSWORD VARCHAR(255) COMMENT '密码;',
    PRIMARY KEY (ID)
) COMMENT = '用户基本信息表';

DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE
(
    ID      VARCHAR(32) NOT NULL COMMENT '关联关系ID;',
    USER_ID VARCHAR(32) COMMENT '用户ID;',
    ROLE_ID VARCHAR(32) COMMENT '角色ID;',
    PRIMARY KEY (ID)
) COMMENT = '用户与角色关联信息表';


CREATE INDEX INDEX_ROLE_USER_ID ON SYS_USER_ROLE (USER_ID);
CREATE INDEX INDEX_USER_ROLE_ID ON SYS_USER_ROLE (ROLE_ID);

DROP TABLE IF EXISTS USER_EXT;
CREATE TABLE USER_EXT
(
    ID         VARCHAR(32) NOT NULL COMMENT '扩展关系ID',
    FIELD_NAME VARCHAR(255) COMMENT '扩展字段显示名称',
    FIELD_TYPE VARCHAR(255) COMMENT '扩展字段数据类型',
    PRIMARY KEY (ID)
) COMMENT = '用户扩展字段表';

DROP TABLE IF EXISTS SYS_PROJECT;
CREATE TABLE SYS_PROJECT
(
    ID          VARCHAR(32)  NOT NULL COMMENT '项目ID',
    NAME        VARCHAR(255) NOT NULL COMMENT '项目名称',
    PREFIX_ID   VARCHAR(255) NOT NULL COMMENT '项目前缀ID',
    OWNER_ID    VARCHAR(32)  NOT NULL COMMENT '项目所有者ID',
    LOGO_URL    VARCHAR(900) NOT NULL COMMENT '项目显示LOGO',
    BE_TEMPLATE VARCHAR(255) NOT NULL DEFAULT 'TYPE_FALSE' COMMENT '是否设置为项目模板',
    DESCRIBLE   VARCHAR(900) COMMENT '项目描述',
    PRIMARY KEY (ID)
) COMMENT = '项目基本信息表';


CREATE INDEX INDEX_PRO_OWNER_ID ON SYS_PROJECT (OWNER_ID);
CREATE INDEX INDEX_PRO_PREFIX_ID ON SYS_PROJECT (PREFIX_ID);
CREATE INDEX INDEX_PRO_NAME ON SYS_PROJECT (NAME);

DROP TABLE IF EXISTS PRO_TEAM_ROLE;
CREATE TABLE PRO_TEAM_ROLE
(
    ID      VARCHAR(32) NOT NULL COMMENT '项目团队角色关系ID',
    PRO_ID  VARCHAR(32) NOT NULL COMMENT '项目ID',
    ROLE_ID VARCHAR(32) NOT NULL COMMENT '角色ID',
    PRIMARY KEY (ID)
) COMMENT = '项目角色信息表';

DROP TABLE IF EXISTS PRO_ROLE_TEAM_USER;
CREATE TABLE PRO_ROLE_TEAM_USER
(
    ID      VARCHAR(32) NOT NULL COMMENT '项目团队关系ID',
    PRO_ID  VARCHAR(32) NOT NULL COMMENT '关联的项目ID',
    ROLE_ID VARCHAR(32) NOT NULL COMMENT '关联的角色ID',
    USER_ID VARCHAR(32) NOT NULL COMMENT '关联的用户ID',
    PRIMARY KEY (ID)
) COMMENT = '项目团队信息表';



DROP TABLE IF EXISTS PRO_EXT_FIELD;
CREATE TABLE PRO_EXT_FIELD
(
    ID             VARCHAR(32)  NOT NULL COMMENT '自定义字段ID',
    PRO_ID         VARCHAR(32)  NOT NULL COMMENT '关联项目ID',
    PRO_FIELD_NAME VARCHAR(255) NOT NULL COMMENT '项目字段名称',
    PRO_FIELD_TYPE VARCHAR(255) NOT NULL COMMENT '项目字段类型',
    BE_EMPTY       VARCHAR(255) NOT NULL DEFAULT 'TYPE_TRUE' COMMENT '是否为空值',
    CREATED_BY     VARCHAR(32) COMMENT '创建人',
    CREATED_TIME   DATETIME COMMENT '创建时间',
    UPDATED_BY     VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME   DATETIME COMMENT '更新时间',
    DEF_VALUE      VARCHAR(255) COMMENT '默认值',
    PRIMARY KEY (ID)
) COMMENT = '项目自定义字段信息表';

DROP TABLE IF EXISTS ISSUE_ITEM;
CREATE TABLE ISSUE_ITEM
(
    ID           VARCHAR(32)  NOT NULL COMMENT '问题ID',
    PREFIX_ID    VARCHAR(255) NOT NULL COMMENT '与项目ID关联生成的编码',
    PRO_ID       VARCHAR(32)  NOT NULL COMMENT '关联项目ID',
    TITLE        VARCHAR(900) NOT NULL COMMENT '问题标题',
    DESC_CONTENT VARCHAR(255) COMMENT '问题描述',
    LINK_ID      VARCHAR(32) COMMENT '链接的问题ID',
    LINK_TYPE    VARCHAR(255) COMMENT '链接的类型',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '问题信息表';

DROP TABLE IF EXISTS PRO_FIELD_ITEM_DATA;
CREATE TABLE PRO_FIELD_ITEM_DATA
(
    ID                  VARCHAR(255) NOT NULL COMMENT '数据ID',
    ISSUE_ID            VARCHAR(32)  NOT NULL COMMENT '关联问题ID',
    PRO_EXT_FIELD_ID    VARCHAR(32)  NOT NULL COMMENT '关联的自定义字段ID',
    PRO_EXT_FIELD_TYPE  VARCHAR(255) NOT NULL COMMENT '关联的自定义字段类型',
    PRO_EXT_FIELD_VALUE VARCHAR(255) COMMENT '关联的自定义字段的数据值',
    CREATED_BY          VARCHAR(32) COMMENT '创建人',
    CREATED_TIME        DATETIME COMMENT '创建时间',
    UPDATED_BY          VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME        DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '项目自定义字段数据表';

DROP TABLE IF EXISTS ISSUE_TAG;
CREATE TABLE ISSUE_TAG
(
    ID           VARCHAR(32)  NOT NULL COMMENT '标记ID',
    ISSUE_ID     VARCHAR(32)  NOT NULL COMMENT '关联问题ID',
    TAG          VARCHAR(255) NOT NULL COMMENT '标记内容',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '问题标记信息表';