spring :
  datasource :
    url : jdbc:mysql://localhost:43306/AYT_AUTH
    username : root
    password : 980804224
    driverClassName : com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml

# JWT
jwt:
  header: Authorization
  secret: AizenSousek
  #token?????
  expiration: 86400
  tokenHead: "Bearer "