spring:
  datasource:
    url: jdbc:mysql://localhost:43306/bigprize
    username: root
    password: 980804224
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:/mapper/*Dao.xml

# JWT
jwt:
  header: Authorization
  secret: AizenSousek
  #token过期时间一天
  expiration: 86400
  tokenHead: "Bearer "